name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: yezz123/setup-uv@v3
      - name: Install dependencies
        run: |
          uv pip install -e .[test]
      - name: Run tests
        run: uv run pytest -q
      - name: Check import
        run: uv python -c "import pksql"
