name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: yezz123/setup-uv@v3
      - name: Install build tools
        run: uv pip install build twine
      - name: Build and check package
        run: |
          uv run python -m build
          uv run twine check dist/*
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Remove the following line for actual publishing
          repository-url: https://test.pypi.org/legacy/
